services:
  - type: web
    name: skillbridge-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run migrate:prod && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8000
      - key: ACCESS_TOKEN_EXPIRES_IN
        value: 1d
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 7d
      - key: DATABASE_URL
        sync: false
      - key: APP_URL
        sync: false
      - key: BETTER_AUTH_SECRET
        sync: false
      - key: BETTER_AUTH_URL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: ACCESS_TOKEN_SECRET
        sync: false
      - key: REFRESH_TOKEN_SECRET
        sync: false
